# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFindcourse():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_findcourse(self):
    # Test name: find_course
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://coursehunter.net/")
    # 2 | setWindowSize | 1366x728 | 
    self.driver.set_window_size(1366, 728)
    # 3 | click | id=pageSearch | 
    self.driver.find_element(By.ID, "pageSearch").click()
    # 4 | type | id=pageSearch | python
    self.driver.find_element(By.ID, "pageSearch").send_keys("python")
    # 5 | click | linkText=Python. Полное руководство | 
   # self.driver.find_element(By.LINK_TEXT, "Python. Полное руководство").click()
  
